language: go

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...
  - if [ "$TRAVIS_TAG" ]; then bash build.sh; fi

deploy:
  - provider: releases
    api-key: $GH_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
